#!/bin/bash

echo "********** WARNING **********"
echo "*   Graphical Application   *"
echo "*****************************"

if xhost >& /dev/null ; then

	bash /opt/PHANTX/zap/zap.sh "$@"

else
	exit 333

fi
